---
- name: gpg keys
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "{{ k8s_repo }}/deb/Release.key"
    - "{{ crio_repo }}/deb/Release.key"

- name: repos
  ansible.builtin.apt_repository:
    repo: "deb {{ item.repo }} /"
    state: present
    filename: "{{ item.name }}"
  loop:
    - { name: "kubernetes", repo: "{{ k8s_repo }}/deb/" }
    - { name: "cri-o", repo: "{{ crio_repo }}/deb/" }

- name: install
  ansible.builtin.apt:
    name:
      - cri-o
    update_cache: yes

- name: skopeo
  ansible.builtin.apt:
    name: skopeo
  when: crio_skopeo

- name: service
  ansible.builtin.service:
    name: crio
    state: started
    enabled: yes

- name: cni plugins
  ansible.builtin.unarchive:
    src: "{{ cni_plugin_url }}"
    dest: /opt/cni/bin
    remote_src: yes
  when: crio_cni

- name: cni config
  ansible.builtin.copy:
    src: 100-crio-bridge.conf
    dest: /etc/cni/net.d/100-crio-bridge.conf
    owner: root
    group: root
    mode: '0644'
  when: crio_cni
